[settings]
timeout = 1000
#provider = "Podman"

[relaychain]
default_image = "docker.io/paritypr/synth-wave:4564-0.9.13-d32f33e0-e8c9dbd4"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  extra_args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  extra_args = [ "--bob" ]

# [[parachains]]
# id = 100
# addToGenesis = true

#   [parachains.collator]
#   name = "collator01"
#   image = "docker.io/paritypr/colander:4564-d32f33e0"
#   command = "adder-collator"

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
